### ISSUE TITLE
Support Swift 3.0

### ISSUE THREAD

**Issue by Sianay** [segment-boneyard/analytics-swift#5]
Hi, would be nice to support swift 3

**Comment by ssoper** [comment]
Found a Swift 3 fork [here](https://github.com/mihai8804858/analytics-swift). Tests appear to pass.

**Comment by f2prateek** [comment]
Agreed, I'll add support for Swift 3 but unfortunately no ETA at this time. PRs welcome however!

**Comment by f2prateek** [comment]
If this is for iOS/tvOS  — I'd recommend using `analytics-ios` as mentioned in our README 
https://github.com/segmentio/analytics-swift#analytics-swift-

analytics-ios  works with Swift https://github.com/segmentio/analytics-ios

**Comment by atom2ueki** [comment]
@f2prateek [https://github.com/segmentio/analytics-ios](url) have any implement sample in swift way ?

**Comment by f2prateek** [comment]
@atom2ueki sorry for the delay - all the tests are written in swift https://github.com/segmentio/analytics-ios/tree/master/AnalyticsTests

**Comment by atom2ueki** [comment]
@f2prateek thanks man!

**Comment by vjujjavarapu-zz** [comment]
@f2prateek  Does this support Swift 3.0 at the moment or is this project abandoned?

**Comment by f2prateek** [comment]
@vjujjavarapu This project does not support Swift 3.0 at the moment. It's not abandoned, if there are any bugs you have with the existing version feel free to raise them and we'll address those. Missing features are not bugs though.

You can use `analytics-ios` as well.

**Comment by vjujjavarapu-zz** [comment]
@f2prateek ty

**Comment by f2prateek** [comment]
Closed by #7
