### ISSUE TITLE
Support Swift 4.*...

### ISSUE THREAD

**Issue by Natelegreat1** [segment-boneyard/analytics-swift#9]
Any plans? :)

**Comment by f2prateek** [comment]
hey @Natelegreat1, not currently - I would check out analytics-ios since it has more features and supports Swift as well!

**Comment by Natelegreat1** [comment]
@f2prateek yeah... I tried it but couldn't get the very first step `SEGAnalyticsConfiguration *configuration = [SEGAnalyticsConfiguration configurationWithWriteKey:@"YOUR_WRITE_KEY"];`
 to stop crashing... 👎 I will post an Issue on the other Repository
